### ISSUE TITLE
Credential Leak

### ISSUE THREAD

**Issue by MuhammetBurakGolec** [acikkaynak/yardim-agi-flutter#107]
Merhaba,

Flutter uygulamanızda API_SECRET_KEY'in açık olmasını önlemek için aşağıdaki adımı uygulayabilirsiniz:

API anahtarlarını güvenli bir şekilde saklamak: API anahtarlarınızı uygulamanızın kaynak kodları içinde saklamamalısınız. Bunun yerine, ortam değişkenlerini kullanarak veya bir dış kaynakta saklayarak güvenli bir şekilde saklamanız gerekir.
Umarım bu fikir yardımcı olur.

MBG

https://github.com/acikkaynak/yardim-agi-flutter/blob/a89e12b72380d93b34db8026b919845a6652ed4a/lib/main.dart#L9-L12

**Comment by easeccy** [comment]
Bunlar public api key
