### ISSUE TITLE
Location permission yardım sayfası

### ISSUE THREAD

**Issue by easeccy** [acikkaynak/yardim-agi-flutter#129]

**Comment by easeccy** [comment]
![image](https://user-images.githubusercontent.com/26852018/217913888-b4b359fd-7635-46ff-963b-d57a192f47a5.png)
Tutorial görselleri app load time'ı azaltmasın. Lazy load olsun.

**Comment by ndalyanlar** [comment]
Tamamlandı fakat ekstra düzenleme için detay text'leri tekrar bi incelenmeli pr'da bekliyor.
