### ISSUE TITLE
Talep Oluştur - Bilgilendirme Popup'ının eklenmesi

### ISSUE THREAD

**Issue by impinar** [acikkaynak/yardim-agi-flutter#145]
Listeleme ekranı açılır. 
Kullanıcı Talep Oluştur butonuna basar. 
Sistem Talep Oluştur ekranını açar, blurlayıp ilk olarak popup'ı açar. 
Popupta 

- Vazgeç'e tıklarsa listeleme ekranına geri dönülür. 
- Yine de oluştur'a basarsa talep oluştur bilgi giriş ekranına devam edilir. 
Tasarım:
https://discord.com/channels/1072074800622739476/1072207398145634446/1073539193084592148

**Comment by bugragoksu** [comment]
https://github.com/acikkaynak/yardim-agi-flutter/pull/147
