### ISSUE TITLE
filter icon should be visible in empty state on desktop sizes

### ISSUE THREAD

**Issue by bugragoksu** [acikkaynak/yardim-agi-flutter#165]

**Comment by bugragoksu** [comment]
https://github.com/acikkaynak/yardim-agi-flutter/pull/166

**Comment by adnanjpg** [comment]
no filter:
<img width="1792" alt="Screenshot 2023-02-10 at 21 39 04" src="https://user-images.githubusercontent.com/54329101/218171576-db6946ca-b86a-473f-88cc-4eeabac64051.png">

a filter with no categories related to the listed demands:
<img width="1792" alt="Screenshot 2023-02-10 at 21 39 11" src="https://user-images.githubusercontent.com/54329101/218171592-524adced-2320-4c7b-b2b8-4c5889479fbe.png">

**Comment by SeniorTurkmen** [comment]
I don't understand why we need this issue?

**Comment by bugragoksu** [comment]
https://discordapp.com/channels/1072074800622739476/1072287682589368410/1073670780879130796 @SeniorTurkmen
