### ISSUE TITLE
Implement sentry error collection

### ISSUE THREAD

**Issue by easeccy** [acikkaynak/yardim-agi-flutter#52]
https://pub.dev/packages/sentry_flutter

**Comment by utkudenis** [comment]
merhabalar, sentry için sunucumuz var mı ? standart impelementasyonunu yapıp gönderebilirim. otomatik topluyor exceptionları ve cihaz bilgilerini

**Comment by utkudenis** [comment]
branch created. Working on sentry-basic-entegration
