### ISSUE TITLE
Talep ekle düzenle sayfası - UI

### ISSUE THREAD

**Issue by easeccy** [acikkaynak/yardim-agi-flutter#75]

**Comment by easeccy** [comment]
![image](https://user-images.githubusercontent.com/26852018/217598596-a0415f70-171e-4b10-8e5f-01da2d5e391c.png)
https://www.figma.com/file/ggMF14osmhGOvKvS0VKuvQ/Yard%C4%B1m-A%C4%9F%C4%B1-App?node-id=2871%3A70684&t=eynQFYRSEedSjovp-0

**Comment by hasaneke** [comment]
aldım

**Comment by hasaneke** [comment]
@easeccy talep ekle ekranı tasarlandı ihtiyaç seçme ekranındayım
