### ISSUE TITLE
SMS Gönderimi Başarısız Hatası

### ISSUE THREAD

**Issue by hasaneke** [acikkaynak/yardim-agi-flutter#78]
Debug mod'da bu hatayı alıyorum
<img width="432" alt="image" src="https://user-images.githubusercontent.com/67066911/217610696-fdf30401-c071-4bf7-8d73-259f0d6ea3ee.png">

**Comment by yurrpt** [comment]
Numaranın başına +90 koyman gerekiyordu projenin son halini alıp tekrar dener misin böyle bir sorun gözükmüyor?

**Comment by SeniorTurkmen** [comment]
Bu çözülmüş olmalı @erolkaftanoglu
